name: observe
dependencies:
  interceptors: ../../prototype/
transformers:
- interceptors
# To debug: uncomment these lines and run `pub build --mode=debug`
# To run: comment these lines (pub run fails otherwise)
- $dart2js:
    $exclude: [web/example.dart, web/example2.dart]
